<?xml version="1.0" encoding="utf-8"?><Database Name="BD_orquideas" Class="Bd_orquideasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=L30;Initial Catalog=BD_orquideas;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BD_orquideasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_habitacion" Member="tb_habitacion">
    <Type Name="tb_habitacion">
      <Column Name="codigo_habitacion" Type="System.String" DbType="NChar(75) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="metros" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="cantidad_camas" Type="System.String" DbType="NChar(25)" CanBeNull="true" />
      <Column Name="costo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="tipo_habitacion" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Association Name="tb_habitacion_tb_detalle_factura" Member="tb_detalle_factura" ThisKey="codigo_habitacion" OtherKey="codigo_habitacion" Type="tb_detalle_factura" />
      <Association Name="tb_tipo_tb_habitacion" Member="tb_tipo" ThisKey="tipo_habitacion" OtherKey="codigo_Tipo" Type="tb_tipo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_tipo" Member="tb_tipo">
    <Type Name="tb_tipo">
      <Column Name="codigo_Tipo" Type="System.String" DbType="NChar(75) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="tb_tipo_tb_habitacion" Member="tb_habitacion" ThisKey="codigo_Tipo" OtherKey="tipo_habitacion" Type="tb_habitacion" />
    </Type>
  </Table>
  <Table Name="dbo.tb_detalle_factura" Member="tb_detalle_factura">
    <Type Name="tb_detalle_factura">
      <Column Name="codigo_detalle" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codigo_reservacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigo_habitacion" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Association Name="tb_habitacion_tb_detalle_factura" Member="tb_habitacion" ThisKey="codigo_habitacion" OtherKey="codigo_habitacion" Type="tb_habitacion" IsForeignKey="true" />
      <Association Name="tb_reservacion_tb_detalle_factura" Member="tb_reservacion" ThisKey="codigo_reservacion" OtherKey="codigo_reservacion" Type="tb_reservacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_reservacion" Member="tb_reservacion">
    <Type Name="tb_reservacion">
      <Column Name="codigo_reservacion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cantidad_de_personas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fecha_finalizacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="codigo_paquete" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="codigo_encabezado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_reservacion_tb_detalle_factura" Member="tb_detalle_factura" ThisKey="codigo_reservacion" OtherKey="codigo_reservacion" Type="tb_detalle_factura" />
      <Association Name="tb_paquete_tb_reservacion" Member="tb_paquete" ThisKey="codigo_paquete" OtherKey="codigo_paquete" Type="tb_paquete" IsForeignKey="true" />
      <Association Name="tb_encabezado_tb_reservacion" Member="tb_encabezado" ThisKey="codigo_encabezado" OtherKey="codigo_encabezado" Type="tb_encabezado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_paquete" Member="tb_paquete">
    <Type Name="tb_paquete">
      <Column Name="codigo_paquete" Type="System.String" DbType="NChar(75) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="costo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_paquete_tb_reservacion" Member="tb_reservacion" ThisKey="codigo_paquete" OtherKey="codigo_paquete" Type="tb_reservacion" />
    </Type>
  </Table>
  <Table Name="dbo.tb_encabezado" Member="tb_encabezado">
    <Type Name="tb_encabezado">
      <Column Name="codigo_encabezado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="numero_documento" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigo_cliente" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Association Name="tb_encabezado_tb_reservacion" Member="tb_reservacion" ThisKey="codigo_encabezado" OtherKey="codigo_encabezado" Type="tb_reservacion" />
      <Association Name="tb_encabezado_tb_reservacion_evento" Member="tb_reservacion_evento" ThisKey="codigo_encabezado" OtherKey="codigo_encabezado" Type="tb_reservacion_evento" />
      <Association Name="tb_cliente_tb_encabezado" Member="tb_cliente" ThisKey="codigo_cliente" OtherKey="codigo_cliente" Type="tb_cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_cliente" Member="tb_cliente">
    <Type Name="tb_cliente">
      <Column Name="codigo_cliente" Type="System.String" DbType="NChar(75) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="tb_tarjeta" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Association Name="tb_cliente_tb_encabezado" Member="tb_encabezado" ThisKey="codigo_cliente" OtherKey="codigo_cliente" Type="tb_encabezado" />
    </Type>
  </Table>
  <Table Name="dbo.tb_reservacion_evento" Member="tb_reservacion_evento">
    <Type Name="tb_reservacion_evento">
      <Column Name="codigo_reservacion_eve" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cantidad_de_personas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_inicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_finalizacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="costo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigo_evento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="codigo_salon" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="codigo_encabezado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_encabezado_tb_reservacion_evento" Member="tb_encabezado" ThisKey="codigo_encabezado" OtherKey="codigo_encabezado" Type="tb_encabezado" IsForeignKey="true" />
      <Association Name="tb_salon_tb_reservacion_evento" Member="tb_salon" ThisKey="codigo_salon" OtherKey="codigo_salon" Type="tb_salon" IsForeignKey="true" />
      <Association Name="tb_evento_tb_reservacion_evento" Member="tb_evento" ThisKey="codigo_evento" OtherKey="codigo_evento" Type="tb_evento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_salon" Member="tb_salon">
    <Type Name="tb_salon">
      <Column Name="codigo_salon" Type="System.String" DbType="NChar(75) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Association Name="tb_salon_tb_reservacion_evento" Member="tb_reservacion_evento" ThisKey="codigo_salon" OtherKey="codigo_salon" Type="tb_reservacion_evento" />
    </Type>
  </Table>
  <Table Name="dbo.tb_evento" Member="tb_evento">
    <Type Name="tb_evento">
      <Column Name="codigo_evento" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="tb_evento_tb_reservacion_evento" Member="tb_reservacion_evento" ThisKey="codigo_evento" OtherKey="codigo_evento" Type="tb_reservacion_evento" />
    </Type>
  </Table>
  <Table Name="dbo.tb_usuarios" Member="tb_usuarios">
    <Type Name="tb_usuarios">
      <Column Name="codigo_usuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
      <Column Name="contraseña" Type="System.String" DbType="NChar(75)" CanBeNull="true" />
    </Type>
  </Table>
</Database>